library(queue)

x <- queue()
str(x)
y <- queue()
str(y)
enqueue(x, 1)
enqueue(y, "a")
enqueue(x, 2)
enqueue(x, 3)
str(x)
str(y)
stopifnot(identical(dequeue(x), 1))
stopifnot(identical(dequeue(x), 2))
stopifnot(identical(dequeue(x), 3))
stopifnot(is.null(dequeue(x)))
z <- list("a", "b")
enqueue(x, z)
stopifnot(identical(dequeue(x), z))
stopifnot(is.null(dequeue(x)))
stopifnot(identical(dequeue(y), "a"))
str(x)
str(y)
